### ISSUE TITLE
got any newbie issues for me?

### ISSUE THREAD

**Issue by ralyodio** [alucao/decon#1]
I just saw your post on HN and am interested, having used nostr but felt the only two libs for it were poorly documented.

**Comment by alucao** [comment]
Hi! Thanks for the interest!
There are some improvements needed:
- The settings page could use some prettier UI.
- The messages page could group chat messages from two people together like regular chat apps instead of just showing messages ordered by date.

**Comment by ralyodio** [comment]
can i just start creating issues as I see fit?

**Comment by alucao** [comment]
Yes, of course.
